[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/BitMask"]

[project]
name = "BitMaskFunctionalities"
version = "1.2.2"
dependencies = ["typing_extensions"]
requires-python = ">= 3.9"
authors = [
    { name = "Adam Thieringer", email = "adamt0408@gmail.com" }
]
description = "A package for creating and manipulating BitMasks"
readme = "README.md"
keywords = ["BitMask", "bitset", "flags", "bit", "data", "binary"]
classifiers = [
    "Development Status :: 5 - Production/Stable"
]
license = "MIT"

[project.urls]
Repository = "https://github.com/AThieringer/BitMask"
Download = "https://github.com/AThieringer/BitMask/releases"
Changelog = "https://github.com/AThieringer/BitMask/blob/master/Changelog"

[tool.bandit]
exclude_dirs = ["tests",]
#skips = ["B101"]
